# -*-python-*-
#
# Copyright 2004-2005 Mark Rose <mkrose@users.sourceforge.net>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

Import('env')

# env = env.Clone()
# env.AppendUnique(CPPDEFINES=Split('OSGCHUNKLOD_LIBRARY'))

# to remove conflicts with MSVCRT
# if env['PLATFORM'].startswith('win'):
#	env.AppendUnique(SHLINKFLAGS=Split('/NODEFAULTLIB:LIBCMT'))


e = env.Clone()
e.ParseConfig('pkg-config --cflags --libs openscenegraph')
e.Append(LIBS = ['GL', 'jpeg', 'pthread'])
e.SharedLibrary('chunklod', [
    'ChunkLod.cpp',
    'ChunkLodDrawable.cpp',
    'ChunkLodLoader.cpp',
    'Module.cpp',
    'RayStrip.cpp',
    'TextureQuadTree.cpp',
    'Version.cpp',
])

#	deps = ['cspsim', 'jpeg'],
#	aliases = ['all', 'clod'],
#	softlink = 1)

