# -*- python -*-
#
# Copyright 2004 Mark Rose <mkrose@users.sourceforge.net>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

Import('env build')

SOURCES = [
	'Systems/AircraftFlightSensors.cpp',
	'Systems/AircraftInputSystem.cpp',
	'Systems/AircraftSimpleFCS.cpp',
	'AircraftObject.cpp',
	'AircraftPhysicsModel.cpp',
	'Animation.cpp',
	'AnimationSequence.cpp',
	'Atmosphere.cpp',
	'BaseDynamics.cpp',
	'BaseScreen.cpp',
	'Channels.cpp',
	'ChunkLodTerrain.cpp',
	'CockpitInterface.cpp',
	'Collision.cpp',
	'Colorspace.cpp',
	'Config.cpp',
	'Console.cpp',
	'ConsoleCommands.cpp',
	'Controller.cpp',
	'CSPSim.cpp',
	'DemeterTerrain.cpp',
	'DoubleChannelMirror.cpp',
	'DynamicObject.cpp',
	'DynamicalSystem.cpp',
	'Engine.cpp',
	'EventMapIndex.cpp',
	'EventMapping.cpp',
	'Exception.cpp',
	'F16/AlphaNumericDisplay.cpp',
	'F16/GroundAvoidanceAdvisory.cpp',
	'F16/UpFrontControls.cpp',
	'F16/DataEntryPage.cpp',
	'F16/PageCNI.cpp',
	'F16/PageLIST.cpp',
	'F16/FLCS.cpp',
	'F16/F16Channels.cpp',
	'F16/F16FlightModel.cpp',
	'F16/F16GearDynamics.cpp',
	'F16/F16HUD.cpp',
	'F16/F16INS.cpp',
	'F16/F16System.cpp',
	'F16/PanelHUD.cpp',
	'F16/Radio.cpp',
	'F16/NavigationSystem.cpp',
	'FlightControlSystem.cpp',
	'FlightDynamics.cpp',
	'FlightModel.cpp',
	'FuelManagementSystem.cpp',
	'GameScreen.cpp',
	'GearAnimation.cpp',
	'glDiagnostics.cpp',
	'HID.cpp',
	'HUD/HUD.cpp',
	'HUD/Tape.cpp',
	'HUD/Text.cpp',
	'HUD/PitchLadder.cpp',
	'InputEvent.cpp',
	'InputInterface.cpp',
	'LandingGear.cpp',
	'LogoScreen.cpp',
	'MenuScreen.cpp',
	'NumericalMethod.cpp',
	'ObjectModel.cpp',
	'PhysicsModel.cpp',
	'Projection.cpp',
	'ScreenInfo.cpp',
	'ScreenInfoManager.cpp',
	'SimpleSceneManager.cpp',
	'Sky.cpp',
	'SmokeEffects.cpp',
	'StabilityFlightModel.cpp',
	'Station.cpp',
	'Stores/DragProfile.cpp',
	'Stores/Projectile.cpp',
	'Stores/Stores.cpp',
	'Stores/StoresDatabase.cpp',
	'Stores/StoresDefinition.cpp',
	'Stores/StoresManagementSystem.cpp',
	'System.cpp',
	'SystemsModel.cpp',
	'TankObject.cpp',
	'TerrainObject.cpp',
	'Theater.cpp',
	'Theater/CustomLayoutModel.cpp',
	'Theater/ElevationCorrection.cpp',
	'Theater/Feature.cpp',
	'Theater/FeatureGroup.cpp',
	'Theater/FeatureGroupList.cpp',
	'Theater/FeatureLayout.cpp',
	'Theater/FeatureObjectModel.cpp',
	'Theater/FeatureQuad.cpp',
	'Theater/FeatureSceneModel.cpp',
	'Theater/IsoContour.cpp',
	'Theater/LayoutTransform.cpp',
	'Theater/Objective.cpp',
	'Theater/RandomBillboardModel.cpp',
	'Theater/RandomForestModel.cpp',
	'ThrustData.cpp',
	'Views/CameraAgent.cpp',
	'Views/CameraKinematics.cpp',
	'Views/ExternalViews.cpp',
	'Views/InternalView.cpp',
	'Views/View.cpp',
	'VirtualScene.cpp',
# --------------------------------------
	'ObjectUpdate.net',
]


cCSP_wrap, cCSP_module = env.Swig('cCSP.i', SWIGINCLUDES='-ICSPSim/Include -ISimData/Include')
INTERFACES = [env.SwigWrapper(cCSP_wrap)]

cCSP = env.SharedLibrary('cCSP', INTERFACES + SOURCES, SHLIBPREFIX='_')
Alias('all', cCSP)

