#!/bin/sh

# imposta i nomi delle dll a ccgnu$VER.dll
VER=5

fix() {
	if [ -f "$1" ]; then
		cat "$1" | sed "s/ccgnu[0-9]\\+\([dD]\?\).\(dll\|lib\)/ccgnu$VER\\1.\\2/gi" > _temp_.dat
		mv -f _temp_.dat "$1"
	fi
}

fix install.bat
fix CCXX.dsp
fix CCXX.rc.in
fix CCXX.rc
fix ../demo/apesock.dsp

