Import("env")

# conf = Configure(env)
# if not conf.CheckLib('sigc-2.0'):
#     print "KAKA"
#     Exit(1)
# env = conf.Finish()
env.Program("csplib_config", "util/Config.cpp")
env.Command("util/Config.h", "csplib_config", "csplib/csplib_config > $TARGET")

env.Append(CPPDEFINES=Split('CSPLIB_EXPORTS'))
env.SharedLibrary('csplib', [
    'data/Archive.cpp',
    'data/DataArchive.cpp',
    'data/DataManager.cpp',
    'data/Date.cpp',
    'data/Enum.cpp',
    'data/External.cpp',
    'data/GeoPos.cpp',
    'data/InterfaceProxy.cpp',
    'data/InterfaceRegistry.cpp',
    'data/Key.cpp',
    'data/LUT.cpp',
    'data/Link.cpp',
    'data/Matrix3.cpp',
    'data/Object.cpp',
    'data/Path.cpp',
    'data/Quat.cpp',
    'data/Real.cpp',
    'data/TypeAdapter.cpp',
    'data/Vector2.cpp',
    'data/Vector3.cpp',

    'net/ClientServer.cpp',
    # 'net/ClientServerMessages.net',
    'net/DispatchHandler.cpp',
    'net/DispatchManager.cpp',
    'net/DispatchTarget.cpp',
    'net/NetRandom.cpp',
    'net/NetworkInterface.cpp',
    'net/NetworkNode.cpp',
    'net/PeerInfo.cpp',
    'net/RecordCodec.cpp',
    'net/RoutingHandler.cpp',
    'net/TaggedRecordRegistry.cpp',

    'numeric/NumericalMethod.cpp',

    'spatial/QuadTree.cpp',

    # 'util/Config.h',
    'util/Exception.cpp',
    'util/FileUtility.cpp',
    'util/HashUtility.cpp',
    'util/LocalUpdate.cpp',
    'util/LogStream.cpp',
    'util/Modules.cpp',
    'util/Noise.cpp',
    'util/Random.cpp',
    'util/SimpleConfig.cpp',
    'util/StringTools.cpp',
    'util/SynchronousUpdate.cpp',
    'util/Testing.cpp',
    'util/Timing.cpp',
    'util/Trace.cpp',
    'util/Version.cpp',
    'util/WeakReferenced.cpp',

    'xml/XmlParser.cpp',
])
