#!/usr/bin/python
#
# Copyright 2004 Mark Rose <mkrose@users.sourceforge.net>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA


"""
Changeset manager for subversion (http://tigris.subversion.org).

Copyright 2004 Mark Rose.  This program is free software; you can
redistributed it and/or modify it under the terms of the GNU General
Public License as published by the Free Software Foundation; either
version 2 of the License, or (at your option) any later version.

Usage: %(prog)s [options] command [args...]

Run "%(prog)s help <command>" for help on a specific command.
"""


# setup CSP
import bootstrap

from CSP.base import app
from CSP.tools import subcmd

def main(args):
  if len(args) < 1:
    app.usage()
    return 0
  command = args[0]
  options = args[1:]
  return subcmd.Command.run(command, options)

app.start(disable_interspersed_args=1)

