# -*- python -*-
#
# Copyright 2004 Mark Rose <mkrose@users.sourceforge.net>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA


Import('env build')


SOURCES = [
	'DataArchive.cpp',
	'DataManager.cpp',
	'Date.cpp',
	'Enum.cpp',
	'ExceptionBase.cpp',
	'External.cpp',
	'FileUtility.cpp',
	'GeoPos.cpp',
	'HashUtility.cpp',
	'InterfaceProxy.cpp',
	'InterfaceRegistry.cpp',
	'Key.cpp',
	'Link.cpp',
	'LogStream.cpp',
	'LUT.cpp',
	'Math.cpp',
	'Matrix3.cpp',
	'Noise.cpp',
	'Object.cpp',
	'Path.cpp',
	'Quat.cpp',
	'Random.cpp',
	'Real.cpp',
	'TaggedRecordRegistry.cpp',
	'ThreadBase.cpp',
	'ThreadLog.cpp',
	'Timing.cpp',
	'Trace.cpp',
	'TypeAdapter.cpp',
	'Vector3.cpp',
	'Version.cpp',
]


config = env.Program('SimDataConfig', ['Config.cpp'])
config_h = env.Command('#SimData/Include/SimData/Config.h', config, '$SOURCES > $TARGET')

cSimData_wrap, cSimData_module = env.Swig('cSimData.i', SWIGINCLUDES='-ISimData/Include')
copy_module = env.CopyFile('#/SimData/SimData/cSimData.py', cSimData_module)
env.Alias(['shared', 'all', 'SimData'], copy_module)
INTERFACES = [env.SwigWrapper(cSimData_wrap)]

shlib = env.SharedLibrary('#/SimData/SimData/cSimData', INTERFACES + SOURCES)
build.MarkVersionSource(env, shlib)
env.Alias(['shared', 'all', 'simdata_shlib', 'SimData'], shlib)

if not build.IsWindows(env):
	stlib = env.StaticLibrary('#/SimData/SimData/SimData', SOURCES)
	build.MarkVersionSource(env, stlib)
	env.Alias(['static', 'simdata_static'], stlib)
	env.Clean('all', stlib)

