# -*- python -*-
#
# Copyright 2004 Mark Rose <mkrose@users.sourceforge.net>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

Import('env build')

SWIGFLAGS = ['-runtime', '-noexcept', '-python', '-c++', '-DSWIG_STD_BACKWARD_COMP']
SHLIBS = ['dl', 'pthread']

MODULES = ['Source', 'SimData/Tests']

def PackageConfig(env):
	print '<< SimData Config >>'
	conf = build.CustomConfigure(env)
	conf.CheckSwig('1.3.20')
	env = conf.Finish()

env = env.Copy(SWIGFLAGS=SWIGFLAGS, SHLIBS=SHLIBS, SHLIBPREFIX='_')
env.AppendUnique(SHLINKFLAGS = '-Wl,-z,lazyload')

env.SetConfig(PackageConfig)
env.Documentation('#/SimData/Doc', '#/SimData/Doc/Doxyfile', '#/SimData/Include/*.{h,i}', '#/SimData/Source/*.cpp')

build.BuildModules(env, MODULES)

runtests_action = Action('python $SOURCE', lambda a,b,c: '\n<<Running SimData Tests>>')
runtests = env.Command('RUNTESTS', 'runtests.py', runtests_action, ENV={'SIMDATA_LOGPRIORITY': '4'})
env.Depends(runtests, 'simdata_shlib')
env.Alias('test', runtests)
