#!/usr/bin/env python

# Copyright 2005 Mark Rose <mkrose@users.sourceforge.net>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

"""
Combat Simulator Project - Interface Map Compiler

Converts interface definitions (.map) to a condensed format used by
the simulation (.hid).

Usage: %(prog)s [options] [infile|-] [outfile|-]
"""

import sys

from csp.base import app
from csp.tools.hid import compiler


def main(args):
	if len(args) > 2:
		app.usage()
		return 1

	outfile = sys.stdout
	if len(args) == 2 and args[1] != '-':
		outfile = args[1]

	if args:
		infile = args[0]
	else:
		infile = '-'

	try:
		compiler.MapCompiler.compile(infile, outfile, include_path=app.options.include_path)
	except compiler.Error, e:
		print str(e)
		return 1

	return 0


if __name__ == '__main__':
	app.addOption('-I', '--include_path', metavar='PATH', action='append', default=[], help='Path to search for included map files.')
	app.start()

