# Wrapper for csp/cspsim/.bin/cspsim.py, which is generated by
# SWIG during the build.

import os
import sys

# this path hack allows the cspsim extension module to be loaded
# transparently from the .bin directory.  extending rather than
# replacing __path__ is necessary for py2exe imports to work.
bin = os.path.join(os.path.dirname(__file__), '.bin')
__path__.append(bin)

try:
	from cspsim_module import *
except ImportError, e:
	sys.stderr.write(str(e))
	sys.stderr.write(
"""
Unable to import cspsim.py from csp/cspsim/.bin.  This file and
and others needed by cspsim are generated during the build.
Check that all targets have been built successfully.  See the
README file for build instructions.
""")
	sys.exit(1)

