# Wrapper for csp/cspsim/.bin/cspsim.py, which is generated by
# SWIG during the build.

import os
import sys

bin = os.path.join(os.path.dirname(__file__), '.bin')
sys.path.insert(0, bin)

try:
	from cspsim import *
except ImportError, e:
	sys.stderr.write(str(e))
	sys.stderr.write(
"""
Unable to import cspsim.py from csp/cspsim/.bin.  This file and
and others needed by cspsim are generatedd during the build.
Check that all targets have been built successfully.  See the
README file for build instructions.
""")
	sys.exit(1)

sys.path = sys.path[1:]

