# -*- python -*-
#
# Copyright 2004-2005 Mark Rose <mkrose@users.sourceforge.net>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

Import('env csplib cspwf')

expenv = env.Clone()
expenv.AppendUnique(CPPDEFINES=Split('CSPSIM_EXPORTS __CSPSIM_EXE__'))

cspsim = expenv.SharedLibrary(
    target = 'cspsim',
    source = Glob('*.cpp') + \
        # Glob('*.net') + \
        Glob('weather/*.cpp') + \
        Glob('weather/clouds/*.cpp') + \
        Glob('theater/*.cpp') + \
        Glob('systems/*.cpp') + \
        Glob('ai/*.cpp') + \
        Glob('input/*.cpp') + \
        Glob('f16/*.cpp') + \
        Glob('stores/*.cpp') + \
        Glob('swig/*.cpp') + \
        Glob('battlefield/*.cpp') + \
        # Glob('battlefield/*.net') + \
        Glob('sound/*.cpp') + \
        Glob('test/*.cpp') + \
        Glob('views/*.cpp') + \
        Glob('hud/*.cpp') + \
        Glob('config/*.cpp') + \
        Glob('sky/*.cpp'))
Depends(cspsim, csplib)
Depends(cspsim, cspwf)
Alias('all', cspsim)
Export('cspsim')

cspsim_module = env.SharedLibrary(
    'cspsim_module',
    source = ['cspsim.i'])
Depends(cspsim_module, cspsim)
Alias('all', cspsim_module)


# build.PythonSharedLibrary(expenv,
# 	name = 'indexserver',
# 	sources = [
# 		'indexserver.i',
# 		'IndexServer.h',
# 		'IndexServer.cpp',
# 		'@cspsim/battlefield',
# 		'@cspsim/config',
# 	],
# 	deps = ['csplib', 'sdl'],
# 	aliases = 'all')

# build.Program(env,
# 	name = 'skydemo',
# 	sources = [
# 		'@cspsim/sky',
# 		'sky/Test.cpp',
# 	],
# 	deps = ['csplib', 'osg'],
# 	aliases = 'skydemo')

# build.Test(env,
# 	name = 'test_PhysicsModel',
# 	sources = [ 'test/test_PhysicsModel.cpp' ],
# 	deps = ['csplib', 'cspsim'],
# 	aliases = ['all'])

