/* Combat Simulator Project
 * Copyright 2004 Mark Rose <mkrose@users.sourceforge.net>
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */

/**
 * @file Config.cpp
 * @brief Generate machine-specific definitions.
 */

#include <iostream>
#include <string>

int main(int, char **argv) {
	int x = 1;
	bool big_endian = false;
	if (*(reinterpret_cast<char*>(&x)) == 0) {
		big_endian = true;
	}
	std::string int16 = (sizeof(short) == 2) ? "short" : "int";
	std::string int32 = (sizeof(int) == 4) ? "int" : "long";

	std::cout << "// Generated by " << argv[0] << " --- do not edit\n\n";

	std::cout << "#if !defined __CSPLIB_UTIL_UNIFORM_H__\n";
	std::cout << "# error \"Never use <csp/lib/util/Config.h> directly; include <csp/lib/util/Uniform.h> instead.\"\n";
	std::cout << "#endif\n\n";

	std::cout << "#ifndef __CSPLIB_UTIL_CONFIG_H__\n";
	std::cout << "#define __CSPLIB_UTIL_CONFIG_H__\n\n";

	std::cout << "#define CSP_BE 4321\n";
	std::cout << "#define CSP_LE 1234\n";
	std::cout << "#define CSP_BYTE_ORDER " << (big_endian ? "CSP_BE" : "CSP_LE") << "\n";
	std::cout << "#define CSP_I16 " << int16 << "\n";
	std::cout << "#define CSP_I32 " << int32 << "\n\n";

	std::cout << "#endif // __CSPLIB_UTIL_CONFIG_H__\n";
	return 0;
}
