env = Environment(CPPPATH='#/../', tools = ['mingw'], CXX = '/usr/bin/x86_64-w64-mingw32-g++')
# env = Environment(CPPPATH='#/../')
env.MergeFlags("!pkg-config sigc++-2.0 --cflags")
env.MergeFlags("-O2 -g -W -Wall -pedantic -Wno-long-long -Wno-deprecated -fno-strict-aliasing -Wno-unused-local-typedefs")

Export("env")

env.SConscript(['csplib/SConscript'])

