# -*-python-*-
#
# Copyright 2003-2005 Mark Rose <mkrose@users.sourceforge.net>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

Import('env build')

build.PythonSharedLibrary(env,
    name = 'layout_module',
    sources = [
        'layout.i',
        'cpp/CspLayoutApplication.cpp',
        'cpp/CspLayoutApplication.h',
        'cpp/DynamicGrid.cpp',
        'cpp/DynamicGrid.h',
        'cpp/FeatureGraph.cpp',
        'cpp/FeatureGraph.h',
        'cpp/Handle.cpp',
        'cpp/Handle.h',
        'cpp/LayoutNodes.cpp',
        'cpp/LayoutNodes.h',
        'cpp/ModelLoader.cpp',
        'cpp/ModelLoader.h',
        'cpp/OsgGraphicsWindow.cpp',
        'cpp/OsgGraphicsWindow.h',
        'cpp/OsgModelWindow.cpp',
        'cpp/OsgModelWindow.h',
        'cpp/OsgSceneWindow.cpp',
        'cpp/OsgSceneWindow.h',
        'cpp/OsgTerrainOverviewManipulator.cpp',
        'cpp/OsgTerrainOverviewManipulator.h',
        'cpp/OsgTerrainOverviewWindow.cpp',
        'cpp/OsgTerrainOverviewWindow.h',
        'cpp/OsgTrackballGraphicsWindow.cpp',
        'cpp/OsgTrackballGraphicsWindow.h',
        'cpp/ReaderWriterGoogleMapsOverview.cpp',
        'cpp/ReaderWriterTiledMapServiceOverview.cpp',
        'cpp/ReaderWriterTiledMapServiceOverview.h',
        'cpp/ReaderWriterVirtualEarthOverview.cpp',
        'cpp/Scene.cpp',
        'cpp/Scene.h',
        'cpp/XmlNode.cpp',
        'cpp/XmlNode.h',
    ],
    deps = ['osg', 'csplib', 'cspsim', 'python'],
    aliases = ['layout2', 'all'])
