# -*- python -*-
#
# Copyright 2004 Mark Rose <mkrose@users.sourceforge.net>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

Import('env build')

def PackageConfig(env):
	print ':: csp.modules.chunklod config'
	conf = build.CustomConfigure(env)
	valid = 1
	valid = conf.CheckOSGVersion('osg', '0.9.6') and valid
	# TODO enable/disable osgNV in config.h
	#valid = conf.CheckOSGVersion('osgNV', '0.5.7') and valid
	#valid = conf.CheckLib('osgNVCg') and valid
	#valid = conf.CheckLib('osgNVParse') and valid
	if not valid:
		print 'Missing dependencies; see http://csp.sf.net/wiki/Current_build_dependencies for more information.'
		Exit(1)
	env = conf.Finish()


env = env.Copy()
env.SetConfig(PackageConfig)

# cspchunklod generates lots of warnings; feel free to clean it up and then
# remove this line
env.RemoveFlags(CXXFLAGS=['-pedantic', '-W'])


SOURCES = [
	'ChunkLod.cpp',
	'ChunkLodDrawable.cpp',
	'ChunkLodLoader.cpp',
	'RayStrip.cpp',
	'TextureQuadTree.cpp',
	'Version.cpp',
]

libchunklod = env.SharedLibrary('chunklod', SOURCES)
Alias(['all', 'chunklod'], [libchunklod])

