# -*- python -*-
#
# Copyright 2004 Mark Rose <mkrose@users.sourceforge.net>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

Import('env build')


env = env.Copy()
env.Append(CPPPATH='#/IndexServer/.bin')

env.Append(LIBS=['simcore'], LIBPATH=['#/SimCore/.bin'])
env.Append(LIBS=['simnet'], LIBPATH=['#/SimNet/.bin'])
env.Append(LIBS=['SimData'], LIBPATH=['#/SimData/SimData'])
env.Append(LIBS=['spatialindex'], LIBPATH=['#/SpatialIndex/.bin'])
env.Append(LIBS=['pthread'])
env.ParseConfig('ccgnu2-config --flags --libs')

#env.Documentation('#/IndexServer/.dox', '#/IndexServer/Doxyfile', '#/IndexServer/*.{h,cpp}')


SOURCES = [
	'Config.cpp',
	'IndexServer.cpp',
]

server = env.Program('IndexServer', SOURCES)
server = env.CopyFile('#/IndexServer/IndexServer', server)
Alias(['all', 'indexserver'], [server])


