# -*- python -*-
#
# Copyright 2004 Mark Rose <mkrose@users.sourceforge.net>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

Import('env build')

def PackageConfig(env):
	print '<< CSPChunkLod Config >>'
	conf = build.CustomConfigure(env)
	conf.CheckOSGVersion('osg', '0.9.6')
	# TODO test the return values and enable/disable osgNV in config.h
	conf.CheckOSGVersion('osgNV', '0.5.7')
	conf.CheckLib('osgNVCg')
	conf.CheckLib('osgNVParse')
	env = conf.Finish()

env = env.Copy()

# cspchunklod generates lots of warnings; feel free to clean it up and then
# remove this line
env.RemoveFlags(CXXFLAGS=['-pedantic', '-W', '-Wall'])

build.UpdateEnvironment(env, config=PackageConfig)

SOURCES = [
	'src/osgChunkLod/ChunkLod.cpp',
	'src/osgChunkLod/ChunkLodDrawable.cpp',
	'src/osgChunkLod/ChunkLodLoader.cpp',
	'src/osgChunkLod/RayStrip.cpp',
	'src/osgChunkLod/TextureQuadTree.cpp',
	'src/osgChunkLod/Version.cpp',
]

libchunklod = env.StaticLibrary('osgChunkLod', SOURCES)
Alias('all', libchunklod)

