# Wrapper for csp/tools/googlemaps/.bin/googlemaps_module.py, which is generated by
# SWIG during the build.

import os
import sys

# this path hack allows the googlemaps extension module to be loaded
# transparently from the .bin directory.  extending rather than
# replacing __path__ is necessary for py2exe imports to work.
bin = os.path.join(os.path.dirname(__file__), '.bin')
__path__.append(bin)

try:
	from googlemaps_module import *
except ImportError, e:
	sys.stderr.write(str(e))
	sys.stderr.write(
"""
Unable to import googlemaps_module.py from csp/tools/googlemaps/.bin.  This file and
and others needed by googlemaps are generated during the build.
Check that the target googlemaps has been built successfully.  See the
README file for build instructions.
""")
	sys.exit(1)

