# -*- python -*-
#
# Copyright 2004 Mark Rose <mkrose@users.sourceforge.net>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

Import('env build')

SOURCES = [
	'DataArchive.cpp',
	'DataManager.cpp',
	'Date.cpp',
	'Enum.cpp',
	'GeoPos.cpp',
	'InterfaceProxy.cpp',
	'InterfaceRegistry.cpp',
	'Key.cpp',
	'LUT.cpp',
	'Link.cpp',
	'Matrix3.cpp',
	'Object.cpp',
	'Path.cpp',
	'Quat.cpp',
	'Real.cpp',
	'TypeAdapter.cpp',
	'Vector3.cpp',
]

TESTS = [
	'test/test_Object.cpp',
]

OBJECTS = build.Apply(env.SharedObject, SOURCES + TESTS)
Return('OBJECTS')

