# -*-python-*-
#
# Copyright 2003-2005 Mark Rose <mkrose@users.sourceforge.net>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

print 'COMBAT SIMULATOR PROJECT - CSP Theater Layout Tool'

import sys
from csp.tools import build

build.CheckSConsVersion('0.9.6')
build.CheckPythonVersion('2.2.0')
build.DevpackConfig.SetMinimumVersion('0.6')

build.ExternalLibrary(
	name = 'osg',
	config = [
		build.PkgConfig(package='openscenegraph', version='1.0.0'),
		build.PkgConfig(package='openthreads', version='1.0.0'),
		build.PkgConfig(package='producer', version='1.0.0'),
		build.DevpackConfig(dlls=['osg', 'osgDB', 'osgFX', 'osgGA', 'osgParticle', 'osgProducer', 'osgText', 'osgUtil', 'OpenThreadsWin32'], headers=[('osg', 'Depth'), ('osgText', 'Font')]),
	])

class PlatformSettings:
	def customize_linux(self, env):
		env['CXXFLAGS'] = '-g -Wall -O2'
		env['SWIGCXXFLAGS'] = '-O2 -g'

settings = build.GlobalSettings()
settings.SWIGFLAGS = '-python -c++'
settings.CXXFILESUFFIX = '.cpp'
settings.CPPPATH = ['.', '#/../../..', build.PYTHON_INCLUDE]
settings.AddPlatformSettings(PlatformSettings)
env = settings.env()

build.SourceGroup(env,
	name = 'layout',
	sources = [
		'cLayout.i',
		'DynamicGrid.cpp',
		'FeatureGraph.cpp',
		'LayoutNodes.cpp',
		'PickHandler.cpp',
		'RegionSelect.cpp',
		'View.cpp',
		'ViewEventHandler.cpp',
	],
	deps = ['osg'])

build.SourceGroup(env,
	name = 'loader',
	sources = [
		'cLoader.i',
		'Handle.cpp',
		'Loader.cpp',
	],
	deps = ['osg'])

build.SharedLibrary(env,
	name = 'cLayout',
	sources = ['@layout'],
	aliases = 'all',
	SHLIBPREFIX = '_')

build.SharedLibrary(env,
	name = 'cLoader',
	sources = ['@loader'],
	aliases = 'all',
	SHLIBPREFIX = '_')

build.BuildRegistry.Configure(env)
build.BuildRegistry.Build()

