# -*- python -*-
#
# Copyright 2004-2005 Mark Rose <mkrose@users.sourceforge.net>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

Import('env build')

expenv = env.Clone()
expenv.AppendUnique(CPPDEFINES=Split('CSPWF_EXPORTS'))

build.SharedLibrary(expenv,
    name = 'cspwf',
    sources = Glob("*.cpp", strings=True) + Glob("*.h", strings=True),
    aliases = ['all', 'cspwf'],
    deps = ['csplib', 'opengl', 'osg', 'sdl', 'sound'],
    softlink = 1)

dox = env.Command(
    target='#cspwf/doxygen_doc/index.html',
    source='#cspwf/cspwf.dox',
    action='doxygen - < ${SOURCE.file} 1>.dox.stdout 2>.dox.stderr',
    chdir='cspwf')
env.Alias('dox', dox)
if env.GetOption('clean'):
    Execute(Delete(Dir("#cspwf/doxygen_doc")))
