# -*-python-*-
#
# Copyright 2003-2005 Mark Rose <mkrose@users.sourceforge.net>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

Import('env')

e = env.Clone()
e.ParseConfig('pkg-config --cflags --libs openscenegraph')
e.Append(LIBS = ['csplib', 'cspsim', 'cspwf'], LIBPATH=['#/csplib', '#/cspsim', '#/cspwf'])
sdl_viewer = e.Program('sdl-viewer', ['Program.cpp', 'SDLViewer.cpp', 'SkyGroup.cpp'])
e.Alias('examples', sdl_viewer)


# build.Program(env,
# 	name = 'sdl-viewer',
# 	sources = [
# 		'Program.cpp',
# 		'SDLViewer.cpp',
# 		'SDLViewer.h',
# 		'SkyGroup.cpp',
# 		'SkyGroup.h',
# 	],
# 	deps = ['osg', 'csplib', 'cspsim', 'demeter'],
# 	aliases = ['examples', 'sdl-viewer'])
