/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.16u-20021025-2105
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#ifndef __InterfaceRegistry_WRAP_H__
#define __InterfaceRegistry_WRAP_H__

class __DIRECTOR__;


#endif /* ___InterfaceRegistry_WRAP_H__ */
